version: '3.5'

services:
  uwang-rest-api:
    container_name: "uwang-rest-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:7001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:6500/uwang-dev
      SPRING_DATASOURCE_USERNAME: bluhabit
      SPRING_DATASOURCE_PASSWORD: Bluehabit2023Baru
      SPRING_JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      SPRING_SMTP_HOST: smtp.gmail.com
      SPRING_SMTP_PORT: 587
      SPRING_SMTP_USERNAME: triannurizkillah@gmail.com
      SPRING_SMTP_PASSWORD: ajmysertmddfnsui
    expose:
      - 8000
    networks:
      - app
#  postgres:
#    image: postgres:14.3
#    environment:
#      POSTGRES_USER: bluehabit
#      POSTGRES_PASSWORD: bluehabit
#      POSTGRES_DB: bluehabit
#    ports:
#      - "5432:5432"
#    restart: always
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"

networks:
  app:
    external: true