server:
  port: 7001
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: Bluehabit2023Baru
  jpa:
    hibernate:
      ddl-auto: update