name: Create Dev Release

on:
  # allow to trigger job manually from UI
  workflow_dispatch:
  # trigger on main branch push (direct or via PR merge)
  push:
    branches:
      - 'development'

permissions:
  contents: read

env:
  DOCKER_USER: ${{ secrets.REGISTRY_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

# Disable parallel execution
concurrency: release

jobs:
  pr-build:
    name: Build Dev Release
    runs-on: ubuntu-latest
    # Required by 'git push'
    permissions:
      checks: write
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generate RELEASE_VERSION var (i.e. v12-63hef73)
      - name: Create Release Version
        run: echo "RELEASE_VERSION=dev${{github.run_number}}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Create but not yet push release tag before Gradle run
      - name: Create Release Tag
        run: |
          git tag ${{env.RELEASE_VERSION}}

      - name: docker login
        run: |
          docker login https://registry.bluhabit.id -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build image
        run: docker build -t registry.bluhabit.id/uwang-rest-api-dev:${{env.RELEASE_VERSION}} . --no-cache

      - name: Push
        run: docker push registry.bluhabit.id/uwang-rest-api-dev:${{env.RELEASE_VERSION}}
      # Pushing release tag only if everything before passed
      - name: Push Release Tag
        run: git push origin ${{env.RELEASE_VERSION}}

  deploy:
    runs-on: ubuntu-latest
    needs: pr-build
    name: Deploy to VPS
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Release Version
        run: echo "RELEASE_VERSION=dev${{github.run_number}}-${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
              cd uwang-rest-api/dev
              docker stop uwang-rest-api-dev
              docker rm uwang-rest-api-dev
              docker pull registry.bluhabit.id/uwang-rest-api-dev:${{env.RELEASE_VERSION}}
              docker run -v ./application.properties:/opt/app.properties --network app-net --name uwang-rest-api-dev -p 7001:7001 --env-file ./.env -d registry.bluhabit.id/uwang-rest-api-dev:${{env.RELEASE_VERSION}}
              docker ps -a
